### ISSUE TITLE
react 16+ 不支持

### ISSUE THREAD

**Issue by lwddsy** [react-ld/react-wx-images-viewer#2]
Uncaught Error: _processChildContext is not available in React 16+. This likely means you have multiple copies of React and are attempting to nest a React 15 tree inside a React 16 tree using unstable_renderSubtreeIntoContainer, which isn't supported. Try to make sure you have only one copy of React (and ideally, switch to ReactDOM.createPortal).

**Comment by lidianhao123** [comment]
@lwddsy 
刚刚发布了 1.0.2 版本，支持 React ^16.0.0 请试用，如有问题随时反馈。

**Comment by lidianhao123** [comment]
本问题已解决，关闭本问题。
