### ISSUE TITLE
快速点击时，diffX值可能为undefined

### ISSUE THREAD

**Issue by linjinying** [react-ld/react-wx-images-viewer#4]
![yy 20180207214809](https://user-images.githubusercontent.com/8152848/35919632-b56bb74a-0c50-11e8-9736-d606f6fdc32f.png)

**Comment by lidianhao123** [comment]
@linjinying 快速点什么位置会出现这个问题呢？

**Comment by linjinying** [comment]
![yy 20180208104527](https://user-images.githubusercontent.com/8152848/35952909-39332b14-0cbd-11e8-9c2e-d160c90e2cdb.png)
就快速点击图片，然后出现这个预览图片，再点击预览图片。整个过程快速点击快速关闭。

**Comment by lidianhao123** [comment]
@linjinying 
感谢提供问题描述，该 issue 已经解决。请使用1.0.4版本。
