### ISSUE TITLE
放大的图片没有还原到初始大小

### ISSUE THREAD

**Issue by gaoguoxin** [react-ld/react-wx-images-viewer#6]
在手动放大了一张图片以后，翻到下一张再翻回来之后，发现图片还是放大的，应该是原来的大小才对

**Comment by lidianhao123** [comment]
@gaoguoxin 现有逻辑就是保持放大状态，目前正在进行新版本开发，将会改成还原图片尺寸（即原来大小）。新版本发布会后我会通知你。

**Comment by lidianhao123** [comment]
@gaoguoxin 新版本已经解决该问题，欢迎更新到1.0.6 进行使用。

**Comment by nelhu** [comment]
已更新到1.0.6， 还是会出现这个问题
